name: Release package

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Pull all tags
        run: git pull --tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Set up NPM
        run: |
          cat << EOF > "$HOME/.npmrc"
          email=my@email.com
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      #   - name: Build
      #     run: npm run build

      # THIS DOES NOT WORK BECAUSE OF MERGE COMMIT - npx lerna publish from-git --no-private --include-merged-tags --yes --loglevel silly
      - name: Publish
        run: |
          npx lerna publish from-package --no-private --include-merged-tags --yes --loglevel silly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
