name: Release package

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      #   - name: Pull all tags
      #     run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      #   - name: Build
      #     run: npm run build

      - name: Publish
        run: |
          npx lerna publish from-git --no-private --include-merged-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
